version: '3'
services:

# Service pour la base de données MySQL
  db:
       image: mysql
       container_name: mysql_db1
       restart: always
       environment:
           - MYSQL_DATABASE=gestion_absence
           - MYSQL_ROOT_PASSWORD=""


 # Service pour l'application Laravel
  gestion_absence:
    image: gestion_absence
    environment:
      - DB_HOST=localhost
      - DB_DATABASE=gestion_absence
      - DB_USERNAME=root
      - DB_PASSWORD=
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

           # Service pour le serveur web Nginx
  nginx:
    image: nginx
    ports:
      - 8001:80
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/ etc/nginx/conf.d/default.conf
    depends_on:
      - gestion_absence








    